# Base configs
baseurl: "https://sachinshrma1.github.io/PortfolioPhotos/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"
image_metadata:
  - name: "File1.jpg"
    title: "beautiful"
    description: >
      HELLO
      A stunning view of the mountains during sunset.

  - name: "File10.jpg"
    title: "City Life"
    description: "The busy streets of downtown at night."
  # Add more images as needed

# UI configs
title: "Photography by Sheetal Bharmaik"
subtitle: "See the world through my eyes!"
author: "Sheetal Bharmaik"
header:
  title: "Photography"
  subtitle: "by Sheetal Bharmaik"
footer:
  name: "Hey there, my name is Sheetal"
  bio: "I am an Engineer by profession. I have a passion for capturing the wild beauty of landscapes and wildlife in their natural habitats. Through my lens, I seek to share the awe and serenity of the outdoors, inspiring others to appreciate and protect the world around us."

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/_ancientbird/"
